# Generated by Django 3.2.7 on 2021-09-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagpack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagpack',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('ordered', 'Ordered')], default='active', max_length=30),
        ),
    ]
