# Generated by Django 3.2.7 on 2021-09-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagpack', '0003_alter_bagpackitem_bagpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagpackitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
