# Generated by Django 3.2.7 on 2021-09-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210905_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantattribute',
            name='quantity',
        ),
        migrations.AddField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
