# Generated by Django 3.2.7 on 2021-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210905_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('out_of_stock', 'Out Of Stock')], default='pending', max_length=30),
        ),
    ]
